INSERT INTO CART (ID) VALUES(1);
INSERT INTO USER (ID,USER_ID, EMAIL, NAME, PASSWORD, CART_ID) VALUES (1, 'tester','ddd@dd','tn','123',1);

INSERT INTO ITEM (ID, AMOUNT, CATEGORY, COLOR, DETAIL, GENDER, IMG, NAME, PRICE, RELEASE, SIZE, STYLE, WEATHER) VALUES (1,3,'셔츠','블랙,화이트,네이비','이쁜 셔츠에요','여성','"../img/merchandise/1.PNG"','다우니 나염 블라우스',30000,'2017-08-17','프리','이국','봄-가을')
INSERT INTO ITEM (ID, AMOUNT, CATEGORY, COLOR, DETAIL, GENDER, IMG, NAME, PRICE, RELEASE, SIZE, STYLE, WEATHER) VALUES (2,5,'바지','옐로,그린,블루','이쁜 바지에요','여성','"../img/merchandise/2.PNG"','푸리나 큰통바지',35000,'2017-08-17','45,55,65','홍대','봄-가을')
INSERT INTO ITEM (ID, AMOUNT, CATEGORY, COLOR, DETAIL, GENDER, IMG, NAME, PRICE, RELEASE, SIZE, STYLE, WEATHER) VALUES (3,2,'코트','블랙,화이트','이쁜 코트에요','여성','"../img/merchandise/3.PNG"','시크코트',70000,'2017-08-17','프리','시크함','가을-겨울')

INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (1, '블랙','100-1','프리',1)
INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (2, '화이트','100-2','프리',1)
INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (3, '네이비','100-3','프리',1)

INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (4, '그린','200-1','45',2)
INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (5, '블루','200-2','65',2)

INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (6, '블랙','300-1','프리',3)
INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (7, '블랙','300-2','프리',3)
INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (8, '화이트','300-3','프리',3)
INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (9, '화이트','300-4','프리',3)
INSERT INTO MERCHANDISE (ID, COLOR, NUMBER, SIZE, ITEM_ID) VALUES (10, '화이트','300-5','프리',3)


