INSERT INTO CATEGORY(ID, PART) VALUES (1,'Shirt')
INSERT INTO CATEGORY(ID, PART) VALUES (2,'Pants')
INSERT INTO CATEGORY(ID, PART) VALUES (3,'Coat')

INSERT INTO ADMIN(ID, EMAIL, NAME) VALUES (1, 'dayong7387@gmail.com', '곽대용')


